/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDialog;
import javax.swing.JPanel;

/**
 *
 * @author student
 */
public class JFrameGlavna extends javax.swing.JFrame {

    /**
     * Creates new form JFrameGlavna
     */
    public JFrameGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarGlavniMeni = new javax.swing.JMenuBar();
        jMenuOperacije = new javax.swing.JMenu();
        jMenuItemUnosMesta = new javax.swing.JMenuItem();
        jMenuItemPrikazMesta = new javax.swing.JMenuItem();
        jMenuItemUnosPoslovnogPartnera = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuOperacije.setText("Operacije");

        jMenuItemUnosMesta.setText("Unos mesta");
        jMenuItemUnosMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosMestaActionPerformed(evt);
            }
        });
        jMenuOperacije.add(jMenuItemUnosMesta);

        jMenuItemPrikazMesta.setText("Prikaz mesta");
        jMenuItemPrikazMesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrikazMestaActionPerformed(evt);
            }
        });
        jMenuOperacije.add(jMenuItemPrikazMesta);

        jMenuItemUnosPoslovnogPartnera.setText("Unos poslovnog partnera");
        jMenuItemUnosPoslovnogPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnosPoslovnogPartneraActionPerformed(evt);
            }
        });
        jMenuOperacije.add(jMenuItemUnosPoslovnogPartnera);

        jMenuBarGlavniMeni.add(jMenuOperacije);

        setJMenuBar(jMenuBarGlavniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemUnosMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosMestaActionPerformed
        JPanel panel=new JPanelUnosMesta();
        JDialog dialog=new JDialog(this, "Unos mesta", true);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosMestaActionPerformed

    private void jMenuItemUnosPoslovnogPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnosPoslovnogPartneraActionPerformed
        JPanel panel=new JPanelUnosPoslovniPartner();
        JDialog dialog=new JDialog(this, "Unos poslovnog partnera", true);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemUnosPoslovnogPartneraActionPerformed

    private void jMenuItemPrikazMestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrikazMestaActionPerformed
        JPanel panel=new JPanelPrikazMesta();
        JDialog dialog=new JDialog(this, "Prikaz mesta", true);
        dialog.add(panel);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemPrikazMestaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarGlavniMeni;
    private javax.swing.JMenuItem jMenuItemPrikazMesta;
    private javax.swing.JMenuItem jMenuItemUnosMesta;
    private javax.swing.JMenuItem jMenuItemUnosPoslovnogPartnera;
    private javax.swing.JMenu jMenuOperacije;
    // End of variables declaration//GEN-END:variables
}
